name: 'Netlify Deploy'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DEPLOY: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Clearing out dir
        run: rm -Rf node_modules package-lock.json
      - name: Running NPM Install
        run: npm install
      - name: Build Production
        run: npm run build
      - uses: jsmrcaga/action-netlify-deploy@master
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: "84ccb107-01be-4b8d-9c6d-b6c153643209"
          NETLIFY_DEPLOY_MESSAGE: "${{ github.event.head_commit.message }}"
          NETLIFY_DEPLOY_TO_PROD: ${{ github.event_name == 'push' && true || false }}
          BUILD_DIRECTORY: dist
