name: 'Netlify Deploy'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DEPLOY: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Deploy on pushes
        if: github.event_name == 'push'
        run: echo "::set-env name=DEPLOY::true"
      - name: Running NPM Install
        run: npm install
      - uses: jsmrcaga/action-netlify-deploy@master
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: "84ccb107-01be-4b8d-9c6d-b6c153643209"
          NETLIFY_DEPLOY_MESSAGE: "${{ github.event.head_commit.message }}"
          NETLIFY_DEPLOY_TO_PROD: ${{ env.DEPLOY }}
          BUILD_DIRECTORY: dist
